import * as Images from 'assets/footer';

const Icons = [
 {
  id: 1,
  url: 'https://www.ebsco.com/',
  title: 'EBSCO Information Services',
  img: Images.EBSCOhost,
  name: 'EBSCO Information Services',
 },
 {
  id: 2,
  url: 'http://www.wokinfo.com/',
  title: 'Web of Science',
  img: Images.WebOfScience,
  name: 'Web of Science',
 },
 {
  id: 3,
  url: 'https://www.ebscohost.com/titleLists/pft-coverage.htm',
  title: "Philosopher's Index",
  img: Images.PhilosophersIndex,
  name: "The Philosopher's Index",
 },
 {
  id: 4,
  url: 'https://www.periodicos.capes.gov.br/',
  title: 'Periódicos CAPES',
  img: Images.CAPES,
  name: 'Portal de Periódicos CAPES/MEC',
 },
 {
  id: 5,
  url: 'https://periodicos.ufpb.br/ojs2/index.php',
  title: 'Portal de Periódicos Científicos da UFPB',
  img: Images.PeriodicosUFPB,
  name: 'Portal de Periódicos Científicos da UFPB',
 },
 {
  id: 6,
  url: 'http://cariniana.ibict.br/',
  title: 'Rede Cariniana - Instituto Brasileiro de Informação em Ciência e Tecnologia',
  img: Images.RedeCariniana,
  name: 'Rede Cariniana',
 },
 {
  id: 7,
  url: 'https://doaj.org/',
  title: 'Directory of Open Access Journals',
  img: Images.DOAJ,
  name: 'DOAJ',
 },
 {
  id: 8,
  url: 'https://diadorim.ibict.br/',
  title: 'Diretório de políticas editoriais das revistas científicas brasileiras',
  img: Images.DIADORIM,
  name: 'DIADORIM',
 },
 {
  id: 9,
  url: 'http://oasisbr.ibict.br/vufind/',
  title: 'Portal brasileiro de publicações científicas em acesso aberto',
  img: Images.oasisbr,
  name: 'oasisbr',
 },
 {
  id: 10,
  url: 'https://www.abecbrasil.org.br/novo/',
  title: 'Associação Brasileira de Editores Científicos',
  img: Images.ABEC,
  name: 'ABEC Brasil',
 },
 {
  id: 11,
  url: 'http://www.anpof.org/portal/',
  title: 'Associação Nacional de Pós-Graduação em Filosofia',
  img: Images.ANPOF,
  name: 'ANPOF',
 },
 {
  id: 12,
  url: 'http://www.sherpa.ac.uk/romeo/index.php',
  title: 'Publisher copyright policies & self-archiving',
  img: Images.SherpaRomeo,
  name: 'SHERPA/RoMEO',
 },
 {
  id: 13,
  url: 'https://clockss.org/',
  title: 'Controlled LOCKSS',
  img: Images.CLOCKSS,
  name: 'CLOCKSS',
 },
 {
  id: 14,
  url: 'http://www.openarchives.org/Register/BrowseSites',
  title: 'OAI-PMH Registered Data Providers',
  img: Images.OpenArchivesInitiative,
  name: 'Open Archives Initiative',
 },
 {
  id: 15,
  url: 'https://www.latindex.org/latindex/inicio',
  title: 'CatáImages Latindex',
  img: Images.Latindex,
  name: 'CatáImages Latindex',
 },
 {
  id: 16,
  url: 'http://clase.unam.mx/',
  title: 'Citas Latinoamericanas en Ciencias Sociales y Humanidades',
  img: Images.CLASE,
  name: 'CLASE',
 },
 {
  id: 17,
  url: 'https://biblat.unam.mx/',
  title: 'Bibliografia Latinoamericana en revistas de investigación científica y social',
  img: Images.Biblat,
  name: 'Biblat',
 },
 {
  id: 18,
  url: 'http://dialnet.unirioja.es/',
  title: 'Fundación Dialnet - Universidad de la Rioja',
  img: Images.Dialnet,
  name: 'Dialnet',
 },
 {
  id: 19,
  url: 'https://dbh.nsd.uib.no/publiseringskanaler/erihplus/index',
  title: 'European Reference Index for the Humanities and Social Sciences',
  img: Images.ERIHPLUS,
  name: 'ERIH PLUS',
 },
 {
  id: 20,
  url: 'http://www.cnen.gov.br/centro-de-informacoes-nucleares/livre',
  title: 'Periódicos de livre acesso',
  img: Images.LivRe,
  name: 'LivRe',
 },
 {
  id: 21,
  url: 'http://www.opensciencedirectory.net/',
  title: 'Open Science Directory',
  img: Images.OpenScienceDirectory,
  name: 'Open Science Directory',
 },
 {
  id: 22,
  url: 'https://www.redib.org/',
  title: 'Red Iberoamericana de Innovación y Conocimiento Cientófico',
  img: Images.REDIB,
  name: 'REDIB',
 },
 {
  id: 23,
  url: 'http://www.sumarios.org/',
  title: 'Sumários de Revistas Brasileiras',
  img: Images.SumariosORG,
  name: 'Sumários.org',
 },
 {
  id: 24,
  url: 'https://scholar.google.com.br/citations?user=rzLghK8AAAAJ',
  title: 'Google Scholar',
  img: Images.GoogleScholar,
  name: 'Google Scholar',
 },
 {
  id: 25,
  url: 'http://oaji.net/journal-detail.html?number=1381',
  title: 'Open Academic Journal Index',
  img: Images.OAJI,
  name: 'OAJI.net',
 },
 {
  id: 26,
  url: 'https://base-search.net/Search/Results?lookfor=etd',
  title: 'Bielefeld Academic Search Engine',
  img: Images.BASE,
  name: 'Bielefeld Academic Search Engine',
 },
 {
  id: 27,
  url: 'https://discover.libraryhub.jisc.ac.uk/',
  title: 'Jisc Library Hub Discover',
  img: Images.JISC,
  name: 'Jisc',
 },
 {
  id: 28,
  url: 'https://rebiun.baratz.es/rebiun/',
  title: 'Red de Biblioteca Universitarias Españolas',
  img: Images.REBIUN,
  name: 'CatáImages REBIUN',
 },
 {
  id: 29,
  url: 'http://www.cnen.gov.br/centro-de-informacoes-nucleares',
  title: 'Centro de Informações Nucleares',
  img: Images.CNEN,
  name: 'CNEN',
 },
 {
  id: 30,
  url: 'http://lib.utep.edu/search/tAufforderung+zum+Tanze./taufforderung+zum+tanze/-3,-1,0,B/browse',
  title: 'The University of Texas at El Paso Library',
  img: Images.UTEP,
  name: 'UTEP',
 },
 {
  id: 31,
  url: 'https://biblio.uottawa.ca/',
  title: 'University of Ottawa',
  img: Images.uOttawa,
  name: 'uOttawa',
 },
 {
  id: 32,
  url: 'https://www.worldcat.org/',
  title: 'WorldCat',
  img: Images.WorldCat,
  name: 'WorldCat',
 },
 {
  id: 33,
  url: 'https://worldwidescience.org/',
  title: 'WorldWideScience',
  img: Images.WorldWideScience,
  name: 'WorldWideScience',
 },
 {
  id: 34,
  url: 'https://www.crossref.org/',
  title: 'Crossref',
  img: Images.Crossref,
  name: 'Crossref',
 },
];

export default Icons;
