interface IconInfo {
    id: number;
    url: string;
    title: string;
    img: string;
    name: string;
}

const Icons: IconInfo[] = [
    {
        id: 1,
        url: 'https://www.ebsco.com/',
        title: 'EBSCO Information Services',
        img: '/images/footer/ebsco.png',
        name: 'EBSCO Information Services',
    },
    {
        id: 2,
        url: 'http://www.wokinfo.com/',
        title: 'Web of Science',
        img: '/images/footer/wos.png',
        name: 'Web of Science',
    },
    {
        id: 3,
        url: 'https://www.ebscohost.com/titleLists/pft-coverage.htm',
        title: "Philosopher's Index",
        img: '/images/footer/pindex.png',
        name: "The Philosopher's Index",
    },
    {
        id: 4,
        url: 'https://www.periodicos.capes.gov.br/',
        title: 'Periódicos CAPES',
        img: '/images/footer/capes.png',
        name: 'Portal de Periódicos CAPES/MEC',
    },
    {
        id: 5,
        url: 'https://periodicos.ufpb.br/ojs2/index.php',
        title: 'Portal de Periódicos Científicos da UFPB',
        img: '/images/footer/ufpb.png',
        name: 'Portal de Periódicos Científicos da UFPB',
    },
    {
        id: 6,
        url: 'http://cariniana.ibict.br/',
        title: 'Rede Cariniana - Instituto Brasileiro de Informação em Ciência e Tecnologia',
        img: '/images/footer/cariniana.png',
        name: 'Rede Cariniana',
    },
    {
        id: 7,
        url: 'https://doaj.org/',
        title: 'Directory of Open Access Journals',
        img: '/images/footer/doaj.png',
        name: 'DOAJ',
    },
    {
        id: 8,
        url: 'https://diadorim.ibict.br/',
        title: 'Diretório de políticas editoriais das revistas científicas brasileiras',
        img: '/images/footer/diadorim.png',
        name: 'DIADORIM',
    },
    {
        id: 9,
        url: 'http://oasisbr.ibict.br/vufind/',
        title: 'Portal brasileiro de publicações científicas em acesso aberto',
        img: '/images/footer/oasis.png',
        name: 'oasisbr',
    },
    {
        id: 10,
        url: 'https://www.abecbrasil.org.br/novo/',
        title: 'Associação Brasileira de Editores Científicos',
        img: '/images/footer/abec.png',
        name: 'ABEC Brasil',
    },
    {
        id: 11,
        url: 'http://www.anpof.org/portal/',
        title: 'Associação Nacional de Pós-Graduação em Filosofia',
        img: '/images/footer/anpof.png',
        name: 'ANPOF',
    },
    {
        id: 12,
        url: 'http://www.sherpa.ac.uk/romeo/index.php',
        title: 'Publisher copyright policies & self-archiving',
        img: '/images/footer/sherpa.png',
        name: 'SHERPA/RoMEO',
    },
    {
        id: 13,
        url: 'https://clockss.org/',
        title: 'Controlled LOCKSS',
        img: '/images/footer/clockss.png',
        name: 'CLOCKSS',
    },
    {
        id: 14,
        url: 'http://www.openarchives.org/Register/BrowseSites',
        title: 'OAI-PMH Registered Data Providers',
        img: '/images/footer/oai.png',
        name: 'Open Archives Initiative',
    },
    {
        id: 15,
        url: 'https://www.latindex.org/latindex/inicio',
        title: 'CatáImages Latindex',
        img: '/images/footer/latindex.png',
        name: 'CatáImages Latindex',
    },
    {
        id: 16,
        url: 'http://clase.unam.mx/',
        title: 'Citas Latinoamericanas en Ciencias Sociales y Humanidades',
        img: '/images/footer/clase.png',
        name: 'CLASE',
    },
    {
        id: 17,
        url: 'https://biblat.unam.mx/',
        title: 'Bibliografia Latinoamericana en revistas de investigación científica y social',
        img: '/images/footer/biblat.png',
        name: 'Biblat',
    },
    {
        id: 18,
        url: 'http://dialnet.unirioja.es/',
        title: 'Fundación Dialnet - Universidad de la Rioja',
        img: '/images/footer/dialnet.png',
        name: 'Dialnet',
    },
    {
        id: 19,
        url: 'https://dbh.nsd.uib.no/publiseringskanaler/erihplus/index',
        title: 'European Reference Index for the Humanities and Social Sciences',
        img: '/images/footer/erihplus.png',
        name: 'ERIH PLUS',
    },
    {
        id: 20,
        url: 'http://www.cnen.gov.br/centro-de-informacoes-nucleares/livre',
        title: 'Periódicos de livre acesso',
        img: '/images/footer/livre.png',
        name: 'LivRe',
    },
    {
        id: 21,
        url: 'http://www.opensciencedirectory.net/',
        title: 'Open Science Directory',
        img: '/images/footer/osd.png',
        name: 'Open Science Directory',
    },
    {
        id: 22,
        url: 'https://www.redib.org/',
        title: 'Red Iberoamericana de Innovación y Conocimiento Científico',
        img: '/images/footer/redib.png',
        name: 'REDIB',
    },
    {
        id: 23,
        url: 'http://www.sumarios.org/',
        title: 'Sumários de Revistas Brasileiras',
        img: '/images/footer/sumarios.png',
        name: 'Sumários.org',
    },
    {
        id: 24,
        url: 'https://scholar.google.com.br/citations?user=rzLghK8AAAAJ',
        title: 'Google Scholar',
        img: '/images/footer/scholar.png',
        name: 'Google Scholar',
    },
    {
        id: 25,
        url: 'http://oaji.net/journal-detail.html?number=1381',
        title: 'Open Academic Journal Index',
        img: '/images/footer/oaji.png',
        name: 'OAJI.net',
    },
    {
        id: 26,
        url: 'https://base-search.net/Search/Results?lookfor=etd',
        title: 'Bielefeld Academic Search Engine',
        img: '/images/footer/base.png',
        name: 'Bielefeld Academic Search Engine',
    },
    {
        id: 27,
        url: 'https://discover.libraryhub.jisc.ac.uk/',
        title: 'Jisc Library Hub Discover',
        img: '/images/footer/jisc.png',
        name: 'Jisc',
    },
    {
        id: 28,
        url: 'https://rebiun.baratz.es/rebiun/',
        title: 'Red de Biblioteca Universitarias Españolas',
        img: '/images/footer/rebiun.png',
        name: 'CatáImages REBIUN',
    },
    {
        id: 29,
        url: 'http://www.cnen.gov.br/centro-de-informacoes-nucleares',
        title: 'Centro de Informações Nucleares',
        img: '/images/footer/cnen.png',
        name: 'CNEN',
    },
    {
        id: 30,
        url: 'http://lib.utep.edu/search/tAufforderung+zum+Tanze./taufforderung+zum+tanze/-3,-1,0,B/browse',
        title: 'The University of Texas at El Paso Library',
        img: '/images/footer/utep.png',
        name: 'UTEP',
    },
    {
        id: 31,
        url: 'https://biblio.uottawa.ca/',
        title: 'University of Ottawa',
        img: '/images/footer/uottawa.png',
        name: 'uOttawa',
    },
    {
        id: 32,
        url: 'https://www.worldcat.org/',
        title: 'WorldCat',
        img: '/images/footer/worldcat.png',
        name: 'WorldCat',
    },
    {
        id: 33,
        url: 'https://worldwidescience.org/',
        title: 'WorldWideScience',
        img: '/images/footer/wws.png',
        name: 'WorldWideScience',
    },
    {
        id: 34,
        url: 'https://www.crossref.org/',
        title: 'Crossref',
        img: '/images/footer/crossref.png',
        name: 'Crossref',
    },
];

export default Icons;
